# 1.3.3. More elaborate arrays
* 1.3.3.1. More data types
    - 1.3.3.1.1 Casting
    - 1.3.3.1.2 Different data type sizes
* 1.3.3.2 Structured data types
* 1.3.3.3 **maskedarray:** dealing with (propagation of) missing data
<br>
## 1.3.3.1. More data types
### 1.3.3.1.1 Casting
"Bigger" type wins in mixed-type operations:

In [1]:
%matplotlib inline
import numpy as np

In [2]:
np.array([1, 2, 3]) + 1.5

array([ 2.5,  3.5,  4.5])

Assignment 永远不会改变被 assignment 的那个东西的类型！

In [3]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [4]:
a[0] = 6.9      # float is truncated to integer

In [5]:
a

array([6, 2, 3])

Forced casts 强制类型转换：

In [6]:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)       # truncates to integer
b

array([1, 1, 1])

Rounding:

In [7]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b         # still floating-point

array([ 1.,  2.,  2.,  2.,  4.,  4.])

In [8]:
c = np.around(a).astype(int)
c

array([1, 2, 2, 2, 4, 4])

In [9]:
c[0] = 999         # is copy, not a view
a[0]

1.2

### 1.3.3.1.2 Different data type sizes
有符号(signed) Integers:
* int8, int16, int32, int64

In [10]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [11]:
np.array([1], dtype=int).dtype

dtype('int64')

无符号 unsigned integers:
* uint8, uint16, uint32, uint64

In [12]:
np.iinfo(np.uint32).max, 2**32 -1

(4294967295, 4294967295)

Floating-point numbers:
* float16, float32, float64(same as **float**), float96(same as **np.longdouble**), float128(same as **np.longdouble**)

In [13]:
np.finfo(np.float64).eps

2.2204460492503131e-16

In [14]:
1 + np.finfo(np.longdouble).eps      #　查看精度

1.0000000000000000001

In [15]:
1+np.finfo(np.longdouble).eps == 1.0     # 他俩并不相等

False

In [16]:
np.float32(1e-8) + np.float32(1) == 1

True

In [17]:
np.float64(1e-8) + np.float64(1) == 1

False

Complex floating-point numbers:
* complex64 128 192 256 (192, 256) is platform-dependent

**Smaller data types**:
<br>
以float32和float64为例：
* 内存和硬盘上所占空间少一半
* 有些操作上，小尺寸可能快点
* **BUT:** 小尺寸有 bigger rounding errors, 有时候会 surprising，能不用小尺寸浮点数就别用

### 1.3.3.2. Structured data types
还用不到，先不看了。感觉是自定义数据类型。

In [18]:
samples = np.zeros((6,), dtype=[('sensor_code', 'S4'),
                                ('position', float), ('value', float)])

In [19]:
samples.ndim

1

In [20]:
samples.shape

(6,)

In [21]:
samples.dtype.names

('sensor_code', 'position', 'value')

In [22]:
samples[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13), 
              ('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

下面的**<font color = red>"|S4"是个啥？？？<font>**，是个字符串吧

In [23]:
samples

array([('ALFA',  1. ,  0.37), ('BETA',  1. ,  0.11), ('TAU',  1. ,  0.13),
       ('ALFA',  1.5,  0.37), ('ALFA',  3. ,  0.11), ('TAU',  1.2,  0.13)], 
      dtype=[('sensor_code', 'S4'), ('position', '<f8'), ('value', '<f8')])

In [24]:
samples['sensor_code']  

array(['ALFA', 'BETA', 'TAU', 'ALFA', 'ALFA', 'TAU'], 
      dtype='|S4')

### 1.3.3.3. maskedarray: dealing with (propagation of) missing data
* For floats one could use NaN’s, but masks work for all types:

In [25]:
x = np.ma.array([1, 2, 3, 4], mask=[0, 1, 0, 1])
x

masked_array(data = [1 -- 3 --],
             mask = [False  True False  True],
       fill_value = 999999)

In [26]:
# np.ma.array   -->罩子array
y = np.ma.array([1, 2, 3, 4], mask=[0, 1, 1, 1])
z = x + y       # 带缺失值的计算

In [27]:
z

masked_array(data = [2 -- -- --],
             mask = [False  True  True  True],
       fill_value = 999999)

In [28]:
z[0], z[1]          # 太搞了

(2, masked)

* Masking versions of common functions:

In [29]:
y = np.ma.sqrt([1, -1, 2, -2])      # mask要起作用了

In [30]:
x = np.sqrt([1, -1, 2, -2])     # 注意nan

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


In [31]:
x

array([ 1.        ,         nan,  1.41421356,         nan])

In [32]:
x[0], x[1]

(1.0, nan)